### ISSUE TITLE
3.5.0 tags/release?

### ISSUE THREAD

**Issue by brenns10** [communi/communi-shared#2]
Hello, I'm updating the communi-desktop package for Arch Linux and I'm missing the communi-shared tags for 3.5.0.  Would you mind pushing them?  Thank you!

(ref: https://github.com/communi/communi-desktop/issues/105)

**Comment by jpnurmi** [comment]
Hi, I've pushed the missing tag: https://github.com/communi/communi-shared/releases/tag/v3.5.0 - thanks!

**Comment by jpnurmi** [comment]
I'll try to remember next time :)

**Comment by brenns10** [comment]
thanks!
