### ISSUE TITLE
v3.6.0 tag

### ISSUE THREAD

**Issue by brenns10** [communi/communi-shared#4]
Hello again :)

I (very rarely) maintain the Arch Linux AUR packaging for libcommuni and communi-desktop. I noticed a 3.6.0 tag for both communi-desktop and libcommuni, and wondered if there should be a corresponding tag/release here?

**Comment by jpnurmi** [comment]
Hello, I tagged the respective sha1 that communi-desktop v3.6.0 is using. Looks like it was a couple of commits behind the head but it doesn't matter because those are just code-style tweaks, basically.

https://github.com/communi/communi-shared/releases/tag/v3.6.0

**Comment by brenns10** [comment]
Thanks! The communi-desktop and libcommuni packages are updated to v3.6.0 on Arch Linux :)
